Fix cross commit
The default cross requires very new Rust version:
error: cannot install package `cross 0.2.5`,
it requires rustc 1.77.2 or newer, while the currently active rustc version is 1.75.0